language: python
python: "3.6"
cache: pip
before_install:
  - pip install pipenv==2018.11.26
  - python -m pipenv.help
install:
  - pipenv --three
  - pipenv run pip install enum34==1.1.6
  - pipenv sync --verbose
script:
  - pipenv graph
