language: python
python: "3.6"
cache: pip
before_install:
  - pip install -U pip
  - pip install pipenv==2018.11.26
  - python -m pipenv.help
install:
  - pipenv sync --verbose
script:
  - pipenv graph
